server:
  port: 0

# 유레카 서버 등록
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true   # Eureka 에 등록
    fetch-registry: true         # 다른 서비스 목록 가져오기

spring:
  application:
    name: member-service
  config:
    import: optional:configserver:http://config-server:8888
