server:
  port: 0

# 유레카 서버 등록
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true   # Eureka 에 등록
    fetch-registry: true         # 다른 서비스 목록 가져오기

spring:
  application:
    name: member-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://localhost:3306/drinkly?allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /api/v1/member/swagger-ui/index.html  # Swagger UI 경로 변경
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
  api-docs:
    path: /api/v1/member/api-docs  # OpenAPI 문서 경로 변경
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  model-and-view-allowed: true
  paths-to-match:
    - /api/v1/member/**
    - /api/v1/member/actuators/health
    - /api/v1/member/actuators/refresh
    - /api/v1/member/actuators/busrefresh

store-service:
  url: http://localhost:8000/api/v1/store